### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by remcohaszing**
Previously only a umd main entrypoint. There was also the non-standard `module` field in `package.json`, which causes issues with various tools. Now the standard `package.json` field `exports` is used to support both native ESM and CJS.

Additionally, the webpack build has been replaced with `tsc`. Instead of bundling `path-browserify`, an import condition is used to select either `path` or `path-browserify`. This means that browser users use `path-browserify`, regardless of whether they use ESM or CJS, whereas others use `path`. Also this means users can deduplicate `path-browserify` if they use it elsewhere in their code base.

The `browser` condition is could be tested using:

```sh
node --conditions browser node_modules/.bin/mocha
```

However, this is currently broken due to https://github.com/browserify/path-browserify/pull/33.

Closes #25
Closes #33
Closes #37

### CODE REVIEW

**Comment by aeschli** [comment]
Thanks for the nice work!

I pushed a small fix for a problem I found when consuming the ESM bits from our webpack scripts. Imports can be node modules, but webpack looks for them on disk. `path` beeing a  built-in node module wasn't found.

The removing of the bundling of `path` has advantages and disadvantages. Before vscode-uri was all selfcontained and easy to consume. I hope that all packages can handle the `imports` syntax.
So maybe it would be on the safer sideto keep the code inlined and just fix the exports.

Also, I update the target to es6. Any objections? @jrieken, that also impacts the commonjs/umd code.

**Comment by aeschli** [comment]
I discussed this with @jrieken. We want to keep the path code inlined and vscode-uri selfcontained

Note that both UMD and ESM variants bundle the path code. They have the identical functionality. It's not that ESM is 'for browsers'. 

Still, the changes to add `exports` and to add `esm/package.json` are good and valuable.

**Comment by remcohaszing** [comment]
Do you want the types to be technically correct or is it sufficient if it works, but is technically not 100% correct?

Dual publishing requires to publish types for both CJS and ESM, but when only using named exports, the package is also usable when only publishing the CJS types.

If it doesn’t have to be 100% correct, #25 can be used as-is. If it does need to be correct, I will need to look into another build tool. [`tsup`](https://github.com/egoist/tsup) should probably work.

**Comment by aeschli** [comment]
Made obsolete by https://github.com/microsoft/vscode-uri/pull/39

**Pull request closed without merging**
