### PR TITLE
Path related utilities for URI

### PR DESCRIPTION
**Pull request by aeschli**
The PR adds path related utilities. This helps when working with URIs for resources in hierarchical file systems

- joinPath
- resolvePath
- basename
- extname 

The implementation is kept simple, and has small differences to what we have in vscode:
- normalizing is not root aware (`/c:/..` is `/`)
- resolve does not remove trailing separators as in NodeJS

### CODE REVIEW

**Review by jrieken — CHANGES_REQUESTED** [review]
Should be using nodejs path module

**Comment by aeschli** [comment]
@jrieken I updated the PR so that path comes in through webpack. UMD and ESM targets are generated. I tested that these work and can be consumed.

**Comment by jrieken** [comment]
Yeah 👯 Only question which remains is if those utils should be on the class as static functions. That's how they would be in the `vscode.Uri` variant

**Review by jrieken — APPROVED** [review]

**Comment by aeschli** [comment]
> That's how they would be in the vscode.Uri variant

That's fine with me too.

Note that  `vscode-uri` already has
`export function uriToFsPath(uri: URI, keepDriveLetterCasing: boolean): string` in the module.

**Comment by jrieken** [comment]
> export function uriToFsPath(uri: URI, keepDriveLetterCasing: boolean): string in the module.

That might have been a copy&paste oversight because that's what we use internally - for different flavours of fsPath

**Comment by aeschli** [comment]
@jrieken Let me know if you prefer the new APIs on URI, and what I should do with `uriToFsPath`.
Otherwise I would merge, publish a new version and start adopting.

**Comment by jrieken** [comment]
On the Uri itself as static function, just like we would do it in `vscode.Uri` (which this module complements). And no need for `uriToFsPath`

**Pull request merged**
